version: "3.3"

services:
  postgres:
    build:
      context: .
      dockerfile: postgres.Dockerfile
    environment:
      - "POSTGRES_DB=test"
      - "POSTGRES_PASSWORD=test"
      - "POSTGRES_USER=test"
  test:
    build:
      context: .
      dockerfile: test.Dockerfile
    depends_on:
    - postgres
    links:
    - postgres
